name: Reusable MyPy

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory to run MyPy in"
        type: string
        default: "."

permissions:
  contents: read

concurrency:
  group: mypy-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mypy:
    name: MyPy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Register MyPy problem matcher
        uses: finki-hub/.github/.github/actions/problem-matchers@main
        with:
          tool: mypy

      - name: Run MyPy
        run: |
          uv sync
          uv run mypy --show-column-numbers --no-color-output .
